spring:
  application:
    name: StockMS

#tomcat server port number
server:
  port: 4569

#Specify the Eureka server details here
#This application will be registerd to Eureka mentioned here
eureka:
  client:
    service-url:
      defaultZone: http://localhost:4567/eureka/	